
########################
# NOTE: the supported definitions are only words core-uncommon on nimi.li.
# idx 0 is the base definition
# idx 1 is the modifier definition
definitions = {

     # NOTE: all CORE are below
     "a": ("ah", "ah"),
     "akesi": ("reptile", "reptilian"),
     "ala": ("nothing", "not"),
     "alasa": ("search", "search"),
     "ale": ("everything", "all"),
     "anpa": ("bottom", "down"),
     "ante": ("difference", "different"),
     "anu": ("<or>", "<or>"), # particles a lil weird
     "awen": ("stay", "continue"),
     "e": ("<object>", "<object>"),
     "en": ("<subject>", "<subject>"),
     "esun": ("trade", "business"),
     "ijo": ("thing", "thing"),
     "ike": ("badness", "bad"),
     "ilo": ("tool", "tool"),
     "insa": ("inside", "internal"),
     "jaki": ("icky", "yucky"),
     "jan": ("person", "personified"),
     "jelo": ("yellow", "yellow"),
     "jo": ("hold", "held"),
     "kala": ("fish", "marine"),
     "kalama": ("sound", "sound"),
     "kama": ("coming", "coming"),
     "kasi": ("plant", "plant"),
     "ken": ("can", "possible"),
     "kepeken": ("using", "use"),
     "kili": ("fruit", "fruity"),
     "kiwen": ("rock", "hard"),
     "ko": ("goo", "soft"),
     "kon": ("gas", "gas"),
     "kule": ("color", "colorful"),
     "kulupu": ("group", "group"),
     "kute": ("listener", "listen"),
     "la": ("context", "context"),
     "lape": ("rest", "sleepy"),
     "laso": ("bluegreen", "bluegreen"),
     "lawa": ("head", "head"),
     "len": ("cloth", "clothed"),
     "lete": ("cold", "cold"),
     "li": ("<verb>", "<verb>"),
     "lili": ("little", "little"),
     "linja": ("stringy", "string"),
     "lipu": ("book", "book"),
     "loje": ("red", "red"),
     "lon": ("exist", "exist"),
     "luka": ("hand", "hand"),
     "lukin": ("eye", "look"),
     "lupa": ("hole", "holey"),
     "ma": ("planet", "ground"),
     "mama": ("parent", "caretakerly"),
     "mani": ("money", "monetary"),
     "mi": ("me", "my"),
     "moku": ("food", "food"),
     "moli": ("death", "dead"),
     "monsi": ("back", "behind"),
     "mu": ("noise", "noise"),
     "mun": ("moon", "moon"),
     "musi": ("game", "fun"),
     "mute": ("amount", "many"),
     "nanpa": ("number", "number"),
     "nasa": ("anomaly", "strange"),
     "nasin": ("pathway", "way"),
     "nena": ("bump", "bumpy"),
     "ni": ("this", "this"),
     "nimi": ("word", "word"),
     "noka": ("foot", "foot"),
     "o": ("command", "should"),
     "olin": ("love", "love"),
     "ona": ("they", "their"),
     "open": ("open", "start"),
     "pakala": ("break", "broken"),
     "pali": ("work", "creaton"),
     "palisa": ("pole", "pole"),
     "pan": ("grain", "grain"),
     "pana": ("give", "given"),
     "pi": ("of", "of"),
     "pilin": ("feel", "feeling"),
     "pimeja": ("black", "dark"),
     "pini": ("close", "end"),
     "pipi": ("bug", "bug"),
     "poka": ("side", "nearby"),
     "poki": ("container", "container"),
     "pona": ("good", "good"),
     "pu": ("pu", "pu"),
     "sama": ("same", "same"),
     "seli": ("fire", "hot"),
     "selo": ("skin", "outer"),
     "seme": ("<what>", "<what>"),
     "sewi": ("sky", "up"),
     "sijelo": ("body", "body"),
     "sike": ("circle", "circular"),
     "sin": ("new", "new"),
     "sina": ("you", "your"),
     "sinpin": ("wall", "front"),
     "sitelen": ("drawing", "drawn"),
     "sona": ("knowledge", "knowledge"),
     "soweli": ("animal", "animal"),
     "suli": ("large", "big"),
     "suno": ("sun", "light"),
     "supa": ("furniture", "furniture"),
     "suwi": ("sweet", "cute"),
     "tan": ("origin", "from"),
     "taso": ("but", "only"),
     "tawa": ("travel", "moving"),
     "telo": ("liquid", "liquid"),
     "tenpo": ("time", "time"),
     "toki": ("conversation", "conversation"),
     "tomo": ("building", "building"),
     "tu": ("two", "two"),
     "unpa": ("sex", "sex"),
     "uta": ("mouth", "mouth"),
     "utala": ("battle", "battle"),
     "walo": ("white", "whitish"),
     "wan": ("one", "one"),
     "waso": ("bird", "birdlike"),
     "wawa": ("power", "powerful"),
     "weka": ("absence", "distant"),
     "wile": ("want", "want"),
     # NOTE: all CORE are above

     # NOTE: all COMMON are below
     "kijetesantakalu": ("racoon", "racoon"),
     "kin": ("extra", "too"),
     "kipisi": ("split", "split"),
     "ku": ("ku", "ku"),
     "leko": ("square", "square"),
     "meli": ("female", "female"),
     "mije": ("male", "male"),
     "misikeke": ("medicine", "medicine"),
     "monsuta": ("monster", "scary"),
     "n": ("hm", "hm"),
     "namako": ("spice", "spicy"),
     "soko": ("mushroom", "mushroom"),
     "tonsi": ("genderqueer", "genderqueer"),
     # NOTE: all COMMON are above

     # NOTE: all UNCOMMON are below
     "ali": ("all", "all"),
     "epiku": ("epic", "epic"),
     "jasima": ("echo", "echo"),
     "lanpan": ("steal", "steal"),
     "linluwi": ("internet", "internet"),
     "majuna": ("old", "old"),
     "meso": ("center", "central"),
     "nimisin": ("(new word)", "(new word)"),
     "oko": ("eye", "eye"),
     "su": ("su", "su"),
     # NOTE: all UNCOMMON are above
}
